### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by NaturalFigurehead** [mattdesl/color-wander#14]
Would anyone be able to help me look over this problem when I do `npm install`?

Not sure how I can fix the errors that occur.

![1](https://cloud.githubusercontent.com/assets/7815878/17672314/5e52830e-62e1-11e6-9fe0-fed9c92ee5f3.png)

![2](https://cloud.githubusercontent.com/assets/7815878/17672319/658467be-62e1-11e6-91ab-31bfed3566e9.png)

log file:
[npm-debug.txt](https://github.com/mattdesl/color-wander/files/418549/npm-debug.txt)

Thanks!

**Comment by ff6347** [comment]
Looks like you are having problems with the cairo install. Take a look at this https://github.com/Automattic/node-canvas/wiki/Installation---Windows#installing-cairo-library

**Comment by NaturalFigurehead** [comment]
Thanks for the reply. I'll look over that link.

**Comment by NaturalFigurehead** [comment]
So I was able to build node-canvas and run the GTK demo application. Still not sure how to bring everything together and install color-wander as I am now getting this response:

C:\Users\Oliver\Documents\GitHub\color-wander>npm install
\

> canvas@1.4.0 install C:\Users\Oliver\Documents\GitHub\color-wander\node_modules\canvas
> node-gyp rebuild

C:\Users\Oliver\Documents\GitHub\color-wander\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
..\src\Canvas.cc(144): warning C4457: declaration of 'data' hides function parameter [C:\Users\Oliver\Documents\GitH
ub\color-wander\node_modules\canvas\build\canvas.vcxproj]
  ..\src\Canvas.cc(140): note: see declaration of 'data'
  win_delay_load_hook.c
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(31): warning C4055: 'type c
ast': from data pointer 'HMODULE' to function pointer 'FARPROC' [C:\Users\Oliver\Documents\GitHub\color-wander\node_
modules\canvas\build\canvas.vcxproj]
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDli
NotifyHook2': redefinition; different type modifiers [C:\Users\Oliver\Documents\GitHub\color-wander\node_modules\can
vas\build\canvas.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDli
  NotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Oliver\Documents\GitHub\color-wander\node_modules\canvas
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.4.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Oliver\Documents\GitHub\color-wander\npm-debug.log

I tried investigating some of the paths it mentioned but they mostly didn't exist.

**Comment by ff6347** [comment]
This seems to be an error with node-canvas. I suggest opening an issue at their repo. https://github.com/Automattic/node-canvas/issues

**Comment by NaturalFigurehead** [comment]
The fix was to update npm.
