### ISSUE TITLE
Thank you - Angular 2 and your permission?

### ISSUE THREAD

**Issue by NathanWalker** [mattdesl/color-wander#6]
Hi @mattdesl thank you for sharing this. It is incredibly inspiring to me. Well all your work is inspiring to me :)

I would like to create an Angular 2 (https://angular.io/) implementation of this if I could have your permission?

Additionally, if you would like to be part of something this weekend (would not require any of your time unless you wanted to), then ping me on Twitter with @wwwalkerrun and I'll fill you in.

**Comment by mattdesl** [comment]
Thanks!

Most of the code here deals with canvas and rendering – how does Angular 2 fit into the picture?

The code is MIT so you can do what you like. But if you ask me, instead of creating a clone, it would be more interesting to fork and remix it to produce different and original results.

**Comment by NathanWalker** [comment]
Thanks @mattdesl Yes we intend to customize and produce lot of different things from this set.
We are actually doing this: 
https://www.angularattack.com/

If you want in (even as a consultant) we have room for 1 more slot.
But yeah, it's Angular thing so we will be componentizing everything here.

**Comment by NathanWalker** [comment]
@mattdesl Thanks again. We were able to customize audiograph and create a public api to componentize audiograph. The color picker in bottom right can be opened to live tweak the colors:
http://48angles.2016.angularattack.io/

Repo (private at moment but should become public in next few days) here: https://github.com/rumblex/angularattack2016-48angles

Hope you like it 👍

**Comment by ghost** [comment]
@NathanWalker  saw audiograph.. Great thing to see when two different projects blending into more awesome stuff.
